#!/usr/bin/env python3
"""Videos largos nuevos para YOUTUBE (16:9 horizontal, monetizables 8+ min).

Temas: "El silencio da miedo" (Silence Pandemic) y "Acaparamiento digital"
(digital hoarding). Ambos en espanol, voz jorge, CTA de suscripcion, BGM.
Reutiliza el pipeline de hacer_videos_youtube.py, sin tocar los largos de
Facebook (videos/youtube es solo el WORKSPACE; el destino es VIDEOS_YOUTUBE).
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import hacer_video_youtube as yy
import hacer_videos_youtube as y

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(PROJECT_ROOT, "videos", "youtube")
DEST = os.path.join(PROJECT_ROOT, "VIDEOS_YOUTUBE", "largos")

VIDEOS = [
    {
        "name": "silencio",
        "bgm": True,
        "voices": ["jorge"],
        "rate": "-8%",
        "scenes": [
            {"ai": "Woman alone in a quiet room in warm evening light, sitting still and calm, phone face-down on the table, cozy home",
             "q": "woman sitting alone room night",
             "text": "El otro día, un estudio les dio a las personas una opción: quedarse un rato a solas con sus propios pensamientos, o hacer cualquier otra cosa. Y la mayoría prefirió no quedarse a solas con la cabeza. Ese dato dice algo incómodo: le tenemos más miedo a nuestros propios pensamientos que a estar quietas.",
             "motion": "zoom-in"},
            {"ai": "Hand reaching for a smartphone glowing in the dark, impulse, close-up",
             "q": "hand smartphone dark",
             "text": "No te lo cuento para asustarte. Te lo cuento porque estás viviendo eso todos los días, sin darte cuenta. Cada vez que el momento se queda en silencio, la mano sale sola a buscar el teléfono. No buscás información: buscás ruido.",
             "motion": "pan-right"},
            {"ai": "Person scrolling phone in an empty quiet bus, loneliness",
             "q": "empty bus person phone",
             "text": "El problema no es el ruido. El problema es que el vacío, el silencio, se volvió un lugar que evitamos por sistema. Como si quedarte quieta, sin nada, fuera peligroso. Y no es peligroso: es incómodo. Y hay una diferencia enorme.",
             "motion": "zoom-out"},
            {"ai": "Dark room, person on sofa with phone light, silhouette",
             "q": "silhouette sofa dark room",
             "text": "Pensalo así: cuando te aburrís diez segundos y agarrás el celular, no fuiste débil. Reapareció algo mucho más fuerte que vos: un reflejo entrenado para que nunca te quedes a solas con lo que pensás. La pregunta no es por qué te aburrís. Es por qué el aburrimiento te da tanto miedo.",
             "motion": "pan-left"},
            {"ai": "Woman in a quiet room looking inward, contemplative, dim light, dusty aura of thoughts",
             "q": "contemplative woman window",
             "text": "Porque en silencio, sin estímulos, aparecen las cosas que postergás. Las decisiones que no querés tomar, los miedos que tapa la lista del día, esa conversación que evitás. En silencio, todo eso sale a saludar. Y tu cabeza prefiere cualquier distracción antes que recibirlo.",
             "light": True,
             "motion": "zoom-in"},
            {"ai": "Seventeenth century portrait of Blaise Pascal, candlelight, serious expression",
             "q": "blaise pascal portrait",
             "text": "Blaise Pascal lo escribió hace cuatrocientos años, y parece la foto del celular: toda la desgracia de los hombres viene de una sola cosa: no saber quedarse quietos en una habitación. No digo que Blaise Pascal fuera mago. Digo que el problema no es nuevo: es viejo, y sigue igual.",
             "motion": "pan-right"},
            {"ai": "Brain neural network, glowing connections in the dark, neuroscience",
             "q": "brain neurons glowing",
             "text": "La ciencia de hoy le pone nombre a lo que Blaise Pascal intuía. Cuando tu mente no tiene estímulos, no se apaga: se enciende. Los neurocientíficos llaman a eso la red neuronal por defecto. No es silencio de muerte: es el motor que trabaja sin pedirte nada.",
             "motion": "zoom-out"},
            {"ai": "Person walking alone through a quiet park at dawn, clear mind",
             "q": "person walking park dawn",
             "text": "En ese modo, la mente hace un trabajo que nadie ve y todos necesitamos: ordena lo vivido, conecta ideas, planea, se acuerda de lo que importa. Es el taller donde se arma el sentido. Y lo habrás notado: las mejores ideas no llegan en la oficina, llegan en la ducha o en la caminata.",
             "light": True,
             "motion": "pan-left"},
            {"ai": "Woman awake at 3am, worried look, dark bedroom, stress",
             "q": "woman sleepless night",
             "text": "El truco es que ese taller necesita vacío para funcionar. Si llenás cada segundo con sonido, scroll y urgencias, el taller no trabaja. Pero el material se acumula. Y la mente tiene que juntarlo de alguna forma: por eso te despertás a las tres de la mañana con todo junto y desordenado.",
             "motion": "zoom-in"},
            {"ai": "Woman sitting calmly in a warm cozy kitchen with a plant and a sleeping cat, morning light, peaceful",
             "q": "woman kitchen plant cat",
             "text": "El estudio lo hizo un psicólogo de Harvard, Tim Wilson. Y el resultado no es que seamos tontos: es que preferimos cualquier estímulo antes que el vacío. El cerebro, sin práctica, le teme al silencio como a un monstruo. Y los monstruos se desactivan con una sola cosa: mirarlos.",
             "motion": "pan-right"},
            {"ai": "Cave with light at the end, silhouettes walking toward the opening",
             "q": "cave light exit",
             "text": "No es que tengas la mente vacía. Es justo al revés: tu mente está tan llena de ruido ajeno que no sabés qué hay abajo tuyo. El silencio no te deja sin nada. El silencio te muestra lo que siempre estuvo, tapado. Eso asusta la primera vez. Y también es, literalmente, el primer paso de salir de la caverna.",
             "light": True,
             "motion": "zoom-out"},
            {"ai": "Person walking with headphones in a busy city, distracted",
             "q": "headphones walker city",
             "text": "Otro estudio, este de la gente que camina: los que caminan sin teléfono, con la mente libre, resuelven más problemas y salen con más claridad que los que entran al edificio con los auriculares puestos. El silencio no es tiempo perdido: es tiempo que trabaja doble, sin que te enteres.",
             "motion": "pan-left"},
            {"ai": "Empty room with a single chair and light beam, minimal still life",
             "q": "empty room chair light",
             "text": "Y acá viene la parte que no se dice: el aburrimiento es la puerta que da a ese taller. La gente que tolera aburrirse un rato desarrolla la capacidad de estar consigo misma. La gente que no lo tolera, se va llenando de distracciones hasta que un día no soporta la soledad ni a solas.",
             "light": True,
             "motion": "zoom-in"},
            {"ai": "Quiet natural landscape, calm lake at dawn, peace",
             "q": "calm lake dawn",
             "text": "No te estoy pidiendo que medites en una montaña. Te pido algo más simple y mucho más difícil: que dejes de tenerle miedo a un momento en blanco. Que el vacío deje de ser un enemigo y empiece a ser un lugar. Eso solo, sin técnicas raras, ya cambia tu día.",
             "light": True,
             "motion": "zoom-out"},
            {"ai": "Ancient Greek amphora and marble column, soft light, hesychia ideal",
             "q": "greek amphora column",
             "text": "Los antiguos lo sabían de memoria. La palabra hesychia, en griego, significa quietud interior, y era, para los griegos, condición de la vida buena. No un lujo de monjes: una práctica básica, como comer o dormir. El que nunca se quedaba quieto, no se conocía.",
             "motion": "pan-right"},
            {"ai": "Roman marble bust of Seneca, dramatic lighting, thoughtful",
             "q": "seneca bust",
             "text": "Séneca, el filósofo romano, escribía desde su silencio. Decía que la soledad no está en no ver gente, sino en no ver nada de lo que pasa adentro. Y que quien no sabe estar con uno mismo, tampoco sabe estar con todo el mundo: porque anda llevándose el ruido a todas partes.",
             "motion": "pan-left"},
            {"ai": "Marble statue of Epictetus, a freed slave philosopher, contemplative",
             "q": "epictetus statue",
             "text": "Epicteto, que fue esclavo, decía una cosa que incomoda: entre lo que te pasa y cómo lo tomás, hay un espacio. Y en ese espacio está tu libertad. Ese espacio no se encuentra en la agenda: se encuentra en silencio, donde nadie te apura y podés tomarte el tiempo de elegir la respuesta.",
             "motion": "zoom-in"},
            {"ai": "Still pond reflecting the moon at night, barro and calm water contrast",
             "q": "pond moon reflection",
             "text": "Hay un refrán japonés que lo dice con una imagen hermosa: un estanque quieto refleja la luna; un estanque agitado, solo barro. El silencio no es suprimir pensamientos: es dejar el agua quieta para ver lo que hay abajo. Y entrenar esa quietud no es magia: es gimnasia.",
             "light": True,
             "motion": "zoom-in"},
            {"ai": "Muscle and brain training concept, dumbbell next to a calm brain",
             "q": "brain training meditation",
             "text": "La gimnasia es la palabra clave. El cerebro se entrena igual que un músculo: si lo ponés en silencio unos minutos por día, al principio incomoda; con repetición, ese lugar empieza a gustar. No es revelación mística: es el hábito de no llenar el vacío.",
             "light": True,
             "motion": "pan-right"},
            {"ai": "Woman in bed before grabbing the phone at sunrise, morning ritual",
             "q": "morning light bed woman",
             "text": "Método, entonces. Paso uno: micro-silencio. Tres minutos cuando te levantás, antes del teléfono. Ni una sola vibración. Solo vos y el día que empieza. Parece poco; es el primer round con el monstruo, y el que define todos los demás.",
             "light": True,
             "motion": "zoom-in"},
            {"ai": "Person standing in a queue, waiting, hands relaxed, no phone",
             "q": "person waiting queue patience",
             "text": "Paso dos: no tapar el aburrimiento. Cuando estés esperando, en la fila, en el transporte, no saques el celular en el primer segundo. Dejate aburrir veinte segundos. Ese fastidio que sentís no es un error: es el caballo moviéndose en el arranque. Aguantalo, y vas a ver cómo al segundo día pesa menos.",
             "light": True,
             "motion": "pan-left"},
            {"ai": "Person walking alone on a quiet road at sunset, no headphones",
             "q": "walking road sunset",
             "text": "Paso tres: una caminata sin auriculares por semana. Veinte minutos, sin podcast, sin música, sin destino. Mirá lo que ves, o no mires nada. El cerebro, en blanco, va a hacer el trabajo que le debés desde hace semanas. Lo echa de menos, te lo juro: es cuestión de darle la chance.",
             "light": True,
             "motion": "zoom-out"},
            {"ai": "Steaming mate or tea cup on a table, quiet cozy morning",
             "q": "tea cup morning",
             "text": "Paso cuatro: el ritual de la ducha o del mate sin teléfono. Un pedazo del día donde no entra ningún estímulo. Tu cabeza necesita ese rato para ordenar lo que a la noche le devuelve con ruidos. Es el embudo que se destapa solo, si le dejás el agua correr.",
             "light": True,
             "motion": "zoom-in"},
            {"ai": "Woman writing in a notebook, one quiet question, introspective",
             "q": "woman notebook writing",
             "text": "Paso cinco: una pregunta en silencio. Cuando estés quieta, hacete una sola: ¿qué me está pesando hoy que no quiero mirarlo? El truco no es resolverlo ahí, ni con prisa. Es hacer visible lo que escondés. Lo que está nombrado, deja de correr como una alarma invisible.",
             "light": True,
             "motion": "pan-right"},
            {"ai": "Gradual growth: small steps from dark to light, hopeful staircase",
             "q": "staircase light hope",
             "text": "No hace falta que empieces con una hora. Ningún músculo crece de un día para otro. Empezá con tres minutos, dejate vencer el aburrimiento, caminá sin ruido una vez a la semana. Eso es método: poco, repetido, sin culpa. Y la ciencia lo apoya: la calma también se entrena, como la fuerza.",
             "light": True,
             "motion": "zoom-in"},
            {"ai": "Quiet pond reflecting the moon again, stillness metaphor, end",
             "q": "still water reflection",
             "text": "Y un consejo de honestidad: no lo cuentes como proeza. El silencio no se vuelve un título para mostrar. Se vuelve un lugar para estar. El que dice que meditó dos horas en las redes, por algo lo cuenta: nadie celebra el estanque quieto, pero el estanque refleja la luna igual.",
             "light": True,
             "motion": "zoom-out"},
            {"ai": "Balanced scene: person enjoying company and also solitude, harmony",
             "q": "harmony balance life",
             "text": "Ojo, no estoy diciendo que tengas que estar sola ni encerrarte. La compañía y el ruido también alimentan. Se trata de proporción: si llenás todo el día con ruido ajeno, no te queda agua quieta para saber qué es tuyo. No es en contra de la vida social: es a favor de la tuya.",
             "light": True,
             "motion": "pan-left"},
            {"ai": "Open air, person breathing calmly, hands relaxed, fresh sky",
             "q": "clear sky breathing calm",
             "text": "La prueba de que lo estás logrando no es sentir paz permanentemente. Es notar que ya no te asusta un momento en blanco. Que podés esperar sin escapar. Que cuando no tenés nada adelante, no hay pánico: hay aire. Ese aire, al principio, parece mucho. Después ya sabés: es tu espacio.",
             "light": True,
             "motion": "zoom-in"},
            {"ai": "Woman with a small dog on her lap by a window at golden hour, flowers on the sill, calm and warm, dawn",
             "q": "woman dog window flowers",
             "text": "Volvamos al principio, para cerrar el círculo. El estudio mostraba que preferimos cualquier cosa antes que el silencio. Hoy ya sabés la diferencia: ese vacío no era peligro, era un lugar. El silencio no está vacío. Está esperando que dejes de mirar el teléfono y mires lo que tenés adentro del pecho.",
             "light": True,
             "motion": "zoom-out"},
            {"ai": "Woman at a window at golden hour at peace, looking inward, warm",
             "q": "woman window golden hour",
             "text": "Empezá hoy con tres minutos. Sin anunciarlo, sin contarlo, sin medallitas. Y una vez al día, recordá: el estanque quieto refleja la luna.",
             "light": True,
             "motion": "zoom-in"},
            {"ai": "Woman smiling softly while holding her phone down, golden hour window light, warm and grateful",
             "q": "woman smiling window calm",
             "text": "Si te sirvió, dale un like, suscribite y contame en comentarios qué te pasa cuando te quedás en silencio. Compartilo con alguien que ande escapando del suyo.",
             "light": True,
             "motion": "zoom-out"},
        ],
    },
    {
        "name": "acaparamiento",
        "bgm": True,
        "voices": ["jorge"],
        "rate": "-8%",
        "scenes": [
            {"ai": "Smartphone screen showing an endless list of saved posts, overwhelming",
             "q": "smartphone saved posts",
             "text": "¿Cuántas cosas guardaste hoy para después? Un post, un video, una receta, un artículo sobre cómo organizar tu vida. La lista de guardados crece como una cuenta que nunca se paga. Y ese hábito, que parece organización, tiene un costo que no ves: te paraliza.",
             "motion": "zoom-in"},
            {"ai": "Digital clutter concept, many open files and icons floating in the dark",
             "q": "digital files clutter",
             "text": "Lo llaman acaparamiento digital: juntar archivos, links, fotos, páginas que no volvés a abrir, pero que no tenés corazón para borrar. No ocupa lugar en tu casa, así que parece gratis. Pero hay un lugar que sí ocupa, y es el peor de todos: tu atención.",
             "motion": "pan-right"},
            {"ai": "Hand opening a smartphone folder full of thousands of saved items",
             "q": "smartphone folder apps",
             "text": "Cada cosa guardada para después es una promesa que te hiciste: algún día lo voy a ver. Y como ese día no llega, la lista crece y crece. Hasta que un día abrís la carpeta de guardados y te abrumás. Cien, quinientos, dos mil ítems. Y en vez de empezar, cerrás la app.",
             "motion": "zoom-out"},
            {"ai": "Person overwhelmed at a desk full of papers and open windows, decision paralysis",
             "q": "overwhelmed desk papers",
             "text": "Ese momento, el de cerrar la app porque hay demasiado, se llama parálisis por opciones. Cuantas más posibilidades juntamos, peor decidimos. No te falta fuerza de voluntad: te falta menos. El exceso no te ayuda: te detiene.",
             "motion": "pan-left"},
            {"ai": "Trapped figure with a heavy invisible backpack, digital weight, dim light",
             "q": "heavy backpack burden",
             "text": "Y fijate lo irónico: guardás todo para no perderte nada, y terminás perdiendo lo más caro, que no es la información: es la decisión. Guardar sin decidir es una manera encubierta de no hacer. Se parece a estar al día, pero es otra forma de procrastinar con pantalla.",
             "motion": "zoom-in"},
            {"ai": "Woman looking at her phone with guilt, quiet room",
             "q": "woman phone guilt",
             "text": "No te cuento esto para que te sientas culpable, que bastante carga ya tenés. Te lo cuento porque es uno de los ruidos de fondo menos nombrados de la vida digital. No es scroll, no es algoritmo: es la mochila que cargás creyendo que es peso muerto. Es método lo que falta, como siempre.",
             "motion": "pan-right"},
            {"ai": "FOMO concept: person looking at others' achievements on screen, envy",
             "q": "fomo social comparison",
             "text": "La ciencia tiene una hipótesis que incomoda: guardamos para reducir la ansiedad de perder algo. Es el miedo a que se nos escape una oportunidad, el famoso miedo a estar perdiéndonos algo, miedo a perderse algo. Guardar nos da una dosis rápida de control.",
             "motion": "zoom-out"},
            {"ai": "Barry Schwartz paradox of choice: supermarket aisle full of many jars, decision fatigue",
             "q": "supermarket many choices",
             "text": "El psicólogo Barry Schwartz estudió la paradoja de elegir: a más opciones, menos satisfacción y más miedo a equivocarse. Y aplicado a tu lista de guardados: cada ítem es una opción que tenés pendiente, una puerta que dejaste entreabierta. Y las puertas entreabiertas no se llaman posibilidades: se llaman fugas de energía.",
             "motion": "pan-left"},
            {"ai": "Collector's cabinet with chosen objects vs cluttered pile, contrast",
             "q": "collection vs pile",
             "text": "Hay una diferencia entre guardar y coleccionar. El coleccionista elige, cuida, decide qué entra y qué se va. El acaparador junta por reflejo: todo entra, nada se examina, nada se va. La diferencia no es el número: es si alguna vez volviste a mirar lo que guardaste. Si no lo volviste a ver, no era una colección: era un depósito.",
             "light": True,
             "motion": "zoom-in"},
            {"ai": "Clock and phone: time being consumed by saved-but-unopened content",
             "q": "clock phone time",
             "text": "Preguntate con honestidad: ¿cuántos de los guardados de hoy vas a abrir esta semana? ¿Cuántos de los de la semana pasada abriste? Cerca de cero. Entonces lo que tenés no son recursos para después: son restos de un reflejo. Y los restos se acumulan hasta que pesan más que lo que valen.",
             "motion": "pan-right"},
            {"ai": "Person saving a course video but not practicing, illusion of progress",
             "q": "saving learning not doing",
             "text": "Y hay una capa más profunda: a veces guardamos algo como sustituto de hacerlo. Guardar el post sobre cómo ahorrar nos hace sentir que ya avanzamos, sin ahorrar. Guardar el video del ejercicio nos da la ilusión de haber entrenado. Guardamos para no hacer. Y la mente lo sabe, y por eso la lista te genera culpa.",
             "motion": "zoom-in"},
            {"ai": "Weighed down shoulders carrying a growing list, tired person",
             "q": "tired burden list",
             "text": "La culpa es el verdadero costo del acaparamiento digital. No es espacio en el disco: es un peso en el pecho. Cada vez que ves la lista larga, sentís que estás atrasada con un montón de cosas. Y no hiciste nada: solo juntaste. Sacar de la lista, decidir, soltar, es lo que te devuelve la liviandad.",
             "motion": "pan-left"},
            {"ai": "Untidy room full of things never used, mirrors inner chaos",
             "q": "messy room clutter",
             "text": "El desorden exterior se refleja en el interior: cuando tu mundo digital está lleno de cabos sueltos, tu cabeza gasta recursos en recordar que debe recordar. No es que no tengas memoria: es que la llenaste de deudas pendientes. Y una deuda pendiente cuesta más que cerrarla.",
             "motion": "zoom-out"},
            {"ai": "Present moment: one thing being truly used now, mindful action",
             "q": "mindful present moment",
             "text": "Lo peor: todo lo que guardás para después, te lo perdés igual. El post que no abrís, el curso que no mirás, la receta que no cocinás: no te aportan nada hoy. El único momento donde algo se puede usar es ahora. Y ahora está tan lleno de pendientes que no hay lugar para lo que elegís de verdad.",
             "light": True,
             "motion": "zoom-in"},
            {"ai": "Ancient Roman library with many scrolls, Seneca idea of books",
             "q": "roman library scrolls",
             "text": "Esto no es un invento moderno. Séneca le escribía a un amigo que juntaba libros para parecer culto: tengo tantos que no he leído, decía, que me pesan como una biblioteca prestada. Y le daba un consejo de dos mil años que parece de hoy: no se trata de cuántos libros tenés, sino de cuántos usás.",
             "motion": "pan-right"},
            {"ai": "A single good book open on a table, used and loved",
             "q": "open book table",
             "text": "El filósofo decía una frase tremenda: la posesión es el precio de la libertad. Cada cosa que juntás sin usar te cobra un pedacito de atención. Y en el mundo digital, la posesión no es una estantería llena: es una lista que abrís en el teléfono. La colección pesa igual, aunque no se vea.",
             "light": True,
             "motion": "zoom-in"},
            {"ai": "Minimalism: fewer, better things on a clean table, stoic ideal",
             "q": "minimal table clean",
             "text": "La tradición estoica lo resumía así: menos, pero mejor. No es no tener nada: es tener lo que sirve y poder soltar lo que no. El que decide qué no entra en su vida, está eligiendo con qué quiere llenarla. Elegir viene siempre acompañado de soltar: es la misma moneda.",
             "light": True,
             "motion": "zoom-out"},
            {"ai": "Person examining and filtering content, deciding, order restored",
             "q": "choosing filtering decision",
             "text": "Y la respuesta a tu lista de guardados no es volverse una persona que no guarda nada. Es la disciplina aristotélica: examinar, ordenar, elegir. No se trata de no guardar nada. Se trata de que lo guardado pase por una decisión tuya. El exceso no se combate con más disciplina suelta: se combate con filtro.",
             "light": True,
             "motion": "pan-right"},
            {"ai": "Strength training metaphor: deciding and letting go like a muscle",
             "q": "training discipline discipline",
             "text": "Porque guardar sin mirar no es mala memoria: es ausencia de criterio. Y el criterio se entrena como un músculo. Cada vez que decidís si algo entra o se va, estás entrenando tu criterio. Cada vez que dejás que entre todo por miedo a perder, lo estás perdiendo a él. Vos elegís qué músculo entrenás.",
             "light": True,
             "motion": "zoom-in"},
            {"ai": "Hand over the phone, deciding not to save, a full stop",
             "q": "hand phone no save",
             "text": "Método, otra vez. Paso uno: un día de guardado cero. Veinticuatro horas sin guardar nada, sin marcar nada, sin salvar nada. Suena elemental, pero vas a ver el reflejo: todos los sentidos en modo juntar. No guardar te obliga a mirar el contenido, no el botón.",
             "light": True,
             "motion": "zoom-out"},
            {"ai": "Calendar week marked, the seven-day rule for saving",
             "q": "calendar week plan",
             "text": "Paso dos: la regla de la semana. Cuando tengas ganas de guardar algo, preguntate: ¿voy a abrir esto esta semana? Si la respuesta es no, no entra. La semana es un plazo honesto: si no lo vas a tocar en siete días, no es para tu vida. El resto es relleno que decide a futuro que no.",
             "light": True,
             "motion": "pan-left"},
            {"ai": "Clear archives after a cleanup, tidy digital files",
             "q": "organized files clean",
             "text": "Paso tres: la auditoría de la lista. Una vez por mes, abrí la carpeta de guardados y mirala como un índice de decisiones. Empezá por las primeras diez: ¿las abriste? Si no, se van. Es la misma prueba que hacés con la ropa del armario: si no lo usaste este año, no te hace falta.",
             "light": True,
             "motion": "zoom-in"},
            {"ai": "Hourglass or clock, waiting two hours before deciding to keep",
             "q": "hourglass time decision",
             "text": "Paso cuatro: el espejo del teléfono. Cuando guardes algo, guardalo dos horas después de haberlo mirado, cuando el impulso pasó. Lo que sobrevive a las dos horas suele ser real; lo que se apaga, era solo el reflejo de no perder. La prisa es el antónimo de la elección.",
             "light": True,
             "motion": "pan-right"},
            {"ai": "Short tidy list, three lines only, minimal roadmap",
             "q": "short list minimal",
             "text": "Paso cinco: límite de una lista de verdad. Tu lista de guardados no es un contenedor infinito de deseos: es una hoja de ruta que se ordena solo si la achicás. Usá un criterio: lo técnico, la inspiración, lo importante. Si no te entra en tres renglones, no va. El filtro no es rigidez: es respeto por tu atención.",
             "light": True,
             "motion": "zoom-in"},
            {"ai": "A mailbox full vs empty inbox concept, attention freed",
             "q": "inbox clear attention",
             "text": "Y el más importante, paso seis: guardar es sacar un turno para atender. Si no hay un turno para atender, no hay turno. Tu lista de guardados no tiene dueño responsable: es un correo sin destinatario. Cada cosa que sacás no es una pérdida: es una página que le devolvés a tu atención.",
             "light": True,
             "motion": "zoom-out"},
            {"ai": "Vertigo on the edge, then calm: letting go of the fear of missing",
             "q": "vertigo calm edge",
             "text": "Probá esto y te va a pasar una cosa rara: al principio, un vértigo leve. Sentís que te estás perdiendo algo. Es el mismo miedo de perder del primer acto, el reflejo del ruido. Dejalo pasar. A la semana, la cabeza está más liviana, decidís más rápido y la lista es chica. Ese es el pago, y no se ve en el teléfono: se ve en tu cara.",
             "light": True,
             "motion": "zoom-in"},
            {"ai": "Three meaningful books vs many unused, wisdom through use",
             "q": "few books used wisdom",
             "text": "No estoy contra guardar. Estoy contra guardar sin mirar. La diferencia entre recursos y peso muerto es exactamente una: la decisión. El que tiene tres libros que leyó, es más sabio que el que tiene trescientos sin abrir. Esa diferencia, en tu lista, la hacés vos.",
             "light": True,
             "motion": "pan-right"},
            {"ai": "Open saved list without panic, calm judgment, light",
             "q": "calm open list",
             "text": "Y la prueba de que cambiaste no es tener la lista vacía. Es que cuando abrís la lista, ya no sentís pánico: sentís criterio. Mirás, elegís, descartás, te quedás con lo que importa. Eso no se nota en una captura: se nota en que dejaste de cargar una mochila invisible.",
             "light": True,
             "motion": "zoom-in"},
            {"ai": "Cycle closing: the full list back, but now chosen with intent",
             "q": "closing circle savings",
             "text": "Volvamos al principio, para cerrar el círculo. Guardás para después y el después nunca llega: la lista crece, la cabeza pesa y no decidís nada. Hoy sabés que no era organización: era el miedo a perder elevado a reflejo. Y que el antídoto no es guardar mejor: es decidir.",
             "light": True,
             "motion": "zoom-out"},
            {"ai": "Calm woman with clear phone, lightness, present moment, warm light",
             "q": "woman clear phone calm",
             "text": "Sacá hoy diez ítems de tu lista de guardados, solo diez, y sentí el peso que se va. Es el primer acto de una cabeza más liviana.",
             "light": True,
             "motion": "zoom-in"},
            {"ai": "Woman smiling softly while holding her phone down, golden hour window light, warm and grateful",
             "q": "woman smiling window calm",
             "text": "Si te sirvió, dale un like, suscribite y contame en comentarios cuántas cosas guardadas tenés y cuántas te animaste a soltar. Compartilo con alguien que ande coleccionando pendientes.",
             "light": True,
             "motion": "zoom-out"},
        ],
    },
]

LIGHT_SCENES = {
    "silencio": {i for i in range(1, 31) if ""},
    "acaparamiento": set(),
}


def build_video_yt(name):
    vid = next(v for v in VIDEOS if v["name"] == name)
    scenes = vid["scenes"]
    if name in LIGHT_SCENES:
        scenes = [
            dict(sc, light=True) if sc.get("light") else dict(sc)
            for sc in scenes
        ]
    vd = {
        "imgs": os.path.join(ROOT, name, "imgs"),
        "audio": os.path.join(ROOT, name, "audio"),
        "out": os.path.join(ROOT, name, "out"),
        "tmp": os.path.join(ROOT, name, "tmp"),
    }
    for d in vd.values():
        os.makedirs(d, exist_ok=True)
    os.makedirs(DEST, exist_ok=True)

    clips = []
    for idx, scene in enumerate(scenes, start=1):
        print(f"[{name}/jorge] escena {idx}/{len(scenes)}", flush=True)
        clips.append(y.build_scene(vd, scene, idx, "jorge", len(scenes),
                                   rate=vid.get("rate", "+0%")))
    out = os.path.join(vd["out"], f"{name}_male.mp4")
    yy.concat(clips, out)
    if vid.get("bgm"):
        bgm = os.path.join(ROOT, "bgm", "ambient.wav")
        y.m.generate_bgm(bgm)
        mixed = out + ".bgm.mp4"
        y.m.mix_bgm(out, bgm, mixed)
        os.replace(mixed, out)
    dur = yy.probe_duration(out)
    final = os.path.join(DEST, f"{name}_male.mp4")
    os.replace(out, final)
    ok = "MONETIZABLE (>=8min)" if dur >= 480 else "corto"
    print(f"OK {final}  {dur/60:.1f} min  [{ok}]", flush=True)


if __name__ == "__main__":
    for name in sys.argv[1:] or [v["name"] for v in VIDEOS]:
        build_video_yt(name)